Add actions.py and parser.py to project
pylover/sunrise pull request #4
Opened 2020-08-02 06:09 UTC by Hhamid1991

Update parser.py file

2020-08-03 10:20 UTC, pylover requested changes

2020-08-03 10:20 UTC, pylover commented on sunrise/actions.py
> +
PEP8

2020-08-11 05:29 UTC, Hhamid1991 commented
Add `ParserError.py` to project and modify `parser.py` and test `parser.py`

2020-08-11 11:05 UTC, pylover requested changes

2020-08-11 11:05 UTC, pylover commented on sunrise/parser.py
> +    ('[-+]?[0-9]+\.?[0-9]*\s*[-+*\/]\s*[-+]?[0-9]+\.?[0-9]*', Calculator)
Use `r'....'` prefix for regex pattern.

2020-08-11 11:05 UTC, pylover commented on sunrise/parser.py
> +    ('[-+]?[0-9]+\.?[0-9]*\s*[-+*\/]\s*[-+]?[0-9]+\.?[0-9]*', Calculator)
Use `re.compile(...)`.

2020-08-11 11:05 UTC, pylover commented on sunrise/parser.py
> +
Use double empty lines.

2020-08-11 11:05 UTC, pylover commented on sunrise/parser.py
> +    raise ParserException(inputstring)
Add an extra blank line above.

2020-08-11 11:05 UTC, pylover commented on sunrise/parser.py
> +        if re.search(pattern, inputstring):
`pattern.search(inputstring)`

2020-08-11 11:05 UTC, pylover commented on sunrise/parser.py
> +        if re.search(pattern, inputstring):
Use `match` instead  of `search`.

2020-08-11 11:05 UTC, pylover commented on sunrise/actions.py
> +class Action :
Unallowed space before `:`.

2020-08-11 11:05 UTC, pylover commented on sunrise/actions.py
> +class Calculator(Action) :
Same as the above.

2020-08-11 11:05 UTC, pylover commented on sunrise/parser.py
> +from sunrise.actions import Calculator
PEP8, input order.

2020-08-12 10:18 UTC, pylover approved these changes

2020-08-12 10:18 UTC, pylover commented on sunrise/parseExceptions.py
> +    def __init__(self, s):
`s`?

2020-08-12 10:22 UTC, merged